#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DQX Puzzle Scanner - the fixed and rebuilt DEUS-QUANTUM-X.

Searches the "~1000 BTC" Bitcoin puzzle ranges (built in: #66-#100, with
#71-#100 as the targets) or any range/address you set yourself.

What changed compared with DEUS-QUANTUM-X
-----------------------------------------
* The modules that never searched anything (GA on address similarity, RL,
  "Grover"/"Shor"/D-Wave stubs, lattice stubs, "self-writing" file copies,
  random "AI predictions") are gone. Hash outputs carry no gradient, so none
  of them can beat an exhaustive scan; they only burned time and crashed.
* Keys are generated by batched elliptic-curve point addition: one modular
  inverse shared by 4096 keys, and each inverse serves both C+iG and C-iG.
  That is about 10-13x faster per core than one scalar multiplication per
  key (the old code), measured at ~275k keys/s/core vs ~21k.
* Compares 20-byte hash160 values, never Base58 strings, and checks every
  target at once (a set lookup).
* Real multi-core (one process per core) with clean Ctrl+C handling.
* Checkpoints are tied to the exact range + chunk size, so changing the range
  can never silently resume a stale position (the old bug).
* A found key is verified independently, written to FOUND_KEYS.txt with WIF,
  fsync'ed, and every worker stops.
* Standard library only. Runs on Linux, macOS and Windows, Python 3.8+.
  RIPEMD-160 falls back to pycryptodome or a built-in pure-Python version if
  your OpenSSL build lacks it.

Commands
--------
  python dqx_scan.py list                     # puzzles, ranges, prizes, odds
  python dqx_scan.py list --online            # + live balance via mempool.space
  python dqx_scan.py selftest                 # proves the scanner on solved puzzles
  python dqx_scan.py bench                    # your keys/s and expected times

  python dqx_scan.py scan --puzzle 71         # one puzzle (random chunks)
  python dqx_scan.py scan --puzzle 71-100     # all unsolved puzzles #71-#100
  python dqx_scan.py scan --puzzle 71 --mode sequential
  python dqx_scan.py scan --puzzle 71 --start 50% --end 60%         # set range
  python dqx_scan.py scan --puzzle 71 --start 0x5a0000000000000000 --end 0x5affffffffffffffff
  python dqx_scan.py scan --puzzle 71 --shard 3/8                    # machine 3 of 8
  python dqx_scan.py scan --address 1BY8GQbnueYofwSuFAT3USAhGjPrkxDdW9 \
                          --start 730fc235c1942c1a0 --end 730fc235c1942c2ae

Positions (--start/--end) are hex (with or without 0x), "dec:<decimal>", or a
percentage of the puzzle range such as "37.5%". Both ends are inclusive.
Progress is saved in dqx_state.db; run the same command again to resume.
Create a file named STOP in the working directory to stop gracefully.

Be realistic: puzzle #71 has 2^70 keys. A CPU in Python checks ~10^6 keys/s;
the public pools scan ~10^11 keys/s. Run `bench` to see the numbers for your
machine before spending electricity.
"""

import argparse
import concurrent.futures as cf
import hashlib
import json
import logging
import multiprocessing as mp
import os
import random
import secrets
import signal
import sqlite3
import sys
import time
import urllib.request
from dataclasses import dataclass, field
from fractions import Fraction
from typing import Dict, List, Optional, Set, Tuple

__version__ = "2.0.0"

log = logging.getLogger("dqx")

###############################################################################
# secp256k1
###############################################################################
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
G = (GX, GY)

Point = Optional[Tuple[int, int]]  # None is the point at infinity


def ec_add(p1: Point, p2: Point) -> Point:
    """Affine point addition (handles doubling and infinity). Setup use only."""
    if p1 is None:
        return p2
    if p2 is None:
        return p1
    x1, y1 = p1
    x2, y2 = p2
    if x1 == x2:
        if (y1 + y2) % P == 0:
            return None
        lam = 3 * x1 * x1 * pow(2 * y1, -1, P) % P
    else:
        lam = (y2 - y1) * pow(x2 - x1, -1, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return x3, (lam * (x1 - x3) - y1) % P


def ec_mul(k: int, pt: Point = G) -> Point:
    """Scalar multiplication k*pt (double-and-add). ~2 ms; used once per chunk."""
    k %= N
    acc: Point = None
    while k:
        if k & 1:
            acc = ec_add(acc, pt)
        pt = ec_add(pt, pt)
        k >>= 1
    return acc


def pubkey_compressed(k: int) -> bytes:
    x, y = ec_mul(k)
    return (b"\x03" if y & 1 else b"\x02") + x.to_bytes(32, "big")


###############################################################################
# Hashing: SHA-256 from hashlib, RIPEMD-160 from the best available backend
###############################################################################
_sha256 = hashlib.sha256


def _ripemd160_pure(data: bytes) -> bytes:
    """Pure-Python RIPEMD-160 (slow; used only if nothing better exists)."""
    def rol(x, n):
        return ((x << n) | (x >> (32 - n))) & 0xFFFFFFFF

    def f(j, x, y, z):
        if j < 16:
            return x ^ y ^ z
        if j < 32:
            return (x & y) | (~x & z)
        if j < 48:
            return (x | ~y) ^ z
        if j < 64:
            return (x & z) | (y & ~z)
        return x ^ (y | ~z)

    rl = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
          7, 4, 13, 1, 10, 6, 15, 3, 12, 0, 9, 5, 2, 14, 11, 8,
          3, 10, 14, 4, 9, 15, 8, 1, 2, 7, 0, 6, 13, 11, 5, 12,
          1, 9, 11, 10, 0, 8, 12, 4, 13, 3, 7, 15, 14, 5, 6, 2,
          4, 0, 5, 9, 7, 12, 2, 10, 14, 1, 3, 8, 11, 6, 15, 13]
    rr = [5, 14, 7, 0, 9, 2, 11, 4, 13, 6, 15, 8, 1, 10, 3, 12,
          6, 11, 3, 7, 0, 13, 5, 10, 14, 15, 8, 12, 4, 9, 1, 2,
          15, 5, 1, 3, 7, 14, 6, 9, 11, 8, 12, 2, 10, 0, 4, 13,
          8, 6, 4, 1, 3, 11, 15, 0, 5, 12, 2, 13, 9, 7, 10, 14,
          12, 15, 10, 4, 1, 5, 8, 7, 6, 2, 13, 14, 0, 3, 9, 11]
    sl = [11, 14, 15, 12, 5, 8, 7, 9, 11, 13, 14, 15, 6, 7, 9, 8,
          7, 6, 8, 13, 11, 9, 7, 15, 7, 12, 15, 9, 11, 7, 13, 12,
          11, 13, 6, 7, 14, 9, 13, 15, 14, 8, 13, 6, 5, 12, 7, 5,
          11, 12, 14, 15, 14, 15, 9, 8, 9, 14, 5, 6, 8, 6, 5, 12,
          9, 15, 5, 11, 6, 8, 13, 12, 5, 12, 13, 14, 11, 8, 5, 6]
    sr = [8, 9, 9, 11, 13, 15, 15, 5, 7, 7, 8, 11, 14, 14, 12, 6,
          9, 13, 15, 7, 12, 8, 9, 11, 7, 7, 12, 7, 6, 15, 13, 11,
          9, 7, 15, 11, 8, 6, 6, 14, 12, 13, 5, 14, 13, 13, 7, 5,
          15, 5, 8, 11, 14, 14, 6, 14, 6, 9, 12, 9, 12, 5, 15, 8,
          8, 5, 12, 9, 12, 5, 14, 6, 8, 13, 6, 5, 15, 13, 11, 11]
    kl = [0x00000000, 0x5A827999, 0x6ED9EBA1, 0x8F1BBCDC, 0xA953FD4E]
    kr = [0x50A28BE6, 0x5C4DD124, 0x6D703EF3, 0x7A6D76E9, 0x00000000]

    h = [0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0]
    msg = data + b"\x80" + b"\x00" * ((55 - len(data)) % 64) + (8 * len(data)).to_bytes(8, "little")
    for off in range(0, len(msg), 64):
        x = [int.from_bytes(msg[off + 4 * i: off + 4 * i + 4], "little") for i in range(16)]
        al, bl, cl, dl, el = h
        ar, br, cr, dr, er = h
        for j in range(80):
            t = (rol((al + f(j, bl, cl, dl) + x[rl[j]] + kl[j >> 4]) & 0xFFFFFFFF, sl[j]) + el) & 0xFFFFFFFF
            al, el, dl, cl, bl = el, dl, rol(cl, 10), bl, t
            t = (rol((ar + f(79 - j, br, cr, dr) + x[rr[j]] + kr[j >> 4]) & 0xFFFFFFFF, sr[j]) + er) & 0xFFFFFFFF
            ar, er, dr, cr, br = er, dr, rol(cr, 10), br, t
        t = (h[1] + cl + dr) & 0xFFFFFFFF
        h[1] = (h[2] + dl + er) & 0xFFFFFFFF
        h[2] = (h[3] + el + ar) & 0xFFFFFFFF
        h[3] = (h[4] + al + br) & 0xFFFFFFFF
        h[4] = (h[0] + bl + cr) & 0xFFFFFFFF
        h[0] = t
    return b"".join(v.to_bytes(4, "little") for v in h)


def _pick_ripemd160():
    """Return (name, fast_proto_or_None, func). fast_proto supports .copy()."""
    try:
        proto = hashlib.new("ripemd160")
        proto.copy().update(b"")
        return "hashlib/OpenSSL", proto, lambda d: hashlib.new("ripemd160", d).digest()
    except (ValueError, TypeError):
        pass
    try:
        from Crypto.Hash import RIPEMD160  # pycryptodome
        return "pycryptodome", None, lambda d: RIPEMD160.new(d).digest()
    except ImportError:
        pass
    return "pure-python (slow: pip install pycryptodome)", None, _ripemd160_pure


RIPEMD_BACKEND, _RMD_PROTO, ripemd160 = _pick_ripemd160()


def hash160(data: bytes) -> bytes:
    return ripemd160(_sha256(data).digest())


###############################################################################
# Base58Check, addresses, WIF
###############################################################################
B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def b58encode(raw: bytes) -> str:
    n = int.from_bytes(raw, "big")
    out = []
    while n:
        n, r = divmod(n, 58)
        out.append(B58[r])
    pad = len(raw) - len(raw.lstrip(b"\x00"))
    return "1" * pad + "".join(reversed(out))


def b58decode(s: str) -> bytes:
    n = 0
    for ch in s:
        i = B58.find(ch)
        if i < 0:
            raise ValueError(f"invalid Base58 character {ch!r}")
        n = n * 58 + i
    pad = len(s) - len(s.lstrip("1"))
    body = n.to_bytes((n.bit_length() + 7) // 8, "big") if n else b""
    return b"\x00" * pad + body


def b58check_encode(payload: bytes) -> str:
    return b58encode(payload + _sha256(_sha256(payload).digest()).digest()[:4])


def b58check_decode(s: str) -> bytes:
    raw = b58decode(s)
    payload, chk = raw[:-4], raw[-4:]
    if len(raw) < 5 or _sha256(_sha256(payload).digest()).digest()[:4] != chk:
        raise ValueError(f"bad Base58Check checksum: {s}")
    return payload


def address_to_hash160(addr: str) -> bytes:
    payload = b58check_decode(addr.strip())
    if len(payload) != 21 or payload[0] != 0x00:
        raise ValueError(f"{addr} is not a mainnet P2PKH (1...) address")
    return payload[1:]


def hash160_to_address(h: bytes) -> str:
    return b58check_encode(b"\x00" + h)


def key_to_address(k: int) -> str:
    return hash160_to_address(hash160(pubkey_compressed(k)))


def key_to_wif(k: int) -> str:
    return b58check_encode(b"\x80" + k.to_bytes(32, "big") + b"\x01")  # compressed


###############################################################################
# Puzzle table (addresses checksum-verified; see `selftest`)
###############################################################################
PUZZLES: Dict[int, str] = {
    66: "13zb1hQbWVsc2S7ZTZnP2G4undNNpdh5so",
    67: "1BY8GQbnueYofwSuFAT3USAhGjPrkxDdW9",
    68: "1MVDYgVaSN6iKKEsbzRUAYFrYJadLYZvvZ",
    69: "19vkiEajfhuZ8bs8Zu2jgmC6oqZbWqhxhG",
    70: "19YZECXj3SxEZMoUeJ1yiPsw8xANe7M7QR",
    71: "1PWo3JeB9jrGwfHDNpdGK54CRas7fsVzXU",
    72: "1JTK7s9YVYywfm5XUH7RNhHJH1LshCaRFR",
    73: "12VVRNPi4SJqUTsp6FmqDqY5sGosDtysn4",
    74: "1FWGcVDK3JGzCC3WtkYetULPszMaK2Jksv",
    75: "1J36UjUByGroXcCvmj13U6uwaVv9caEeAt",
    76: "1DJh2eHFYQfACPmrvpyWc8MSTYKh7w9eRF",
    77: "1Bxk4CQdqL9p22JEtDfdXMsng1XacifUtE",
    78: "15qF6X51huDjqTmF9BJgxXdt1xcj46Jmhb",
    79: "1ARk8HWJMn8js8tQmGUJeQHjSE7KRkn2t8",
    80: "1BCf6rHUW6m3iH2ptsvnjgLruAiPQQepLe",
    81: "15qsCm78whspNQFydGJQk5rexzxTQopnHZ",
    82: "13zYrYhhJxp6Ui1VV7pqa5WDhNWM45ARAC",
    83: "14MdEb4eFcT3MVG5sPFG4jGLuHJSnt1Dk2",
    84: "1CMq3SvFcVEcpLMuuH8PUcNiqsK1oicG2D",
    85: "1Kh22PvXERd2xpTQk3ur6pPEqFeckCJfAr",
    86: "1K3x5L6G57Y494fDqBfrojD28UJv4s5JcK",
    87: "1PxH3K1Shdjb7gSEoTX7UPDZ6SH4qGPrvq",
    88: "16AbnZjZZipwHMkYKBSfswGWKDmXHjEpSf",
    89: "19QciEHbGVNY4hrhfKXmcBBCrJSBZ6TaVt",
    90: "1L12FHH2FHjvTviyanuiFVfmzCy46RRATU",
    91: "1EzVHtmbN4fs4MiNk3ppEnKKhsmXYJ4s74",
    92: "1AE8NzzgKE7Yhz7BWtAcAAxiFMbPo82NB5",
    93: "17Q7tuG2JwFFU9rXVj3uZqRtioH3mx2Jad",
    94: "1K6xGMUbs6ZTXBnhw1pippqwK6wjBWtNpL",
    95: "19eVSDuizydXxhohGh8Ki9WY9KsHdSwoQC",
    96: "15ANYzzCp5BFHcCnVFzXqyibpzgPLWaD8b",
    97: "18ywPwj39nGjqBrQJSzZVq2izR12MDpDr8",
    98: "1CaBVPrwUxbQYYswu32w7Mj4HR4maNoJSX",
    99: "1JWnE6p6UN7ZJBN7TtcbNDoRcjFtuDWoNL",
    100: "1KCgMv8fo2TPBpddVi9jqmMmcne9uSNJ5F",
}

# Solved and emptied, as known in mid-2026. #75/#80/.../#100 had their public
# keys exposed and fell to Pollard's kangaroo years ago. Re-check any time with
# `list --online`.
KNOWN_SOLVED: Set[int] = {66, 67, 68, 69, 70, 75, 80, 85, 90, 95, 100}

# Published keys of solved puzzles; `selftest` re-derives their addresses and
# finds them with the real scanner.
SOLVED_KEYS: Dict[int, int] = {
    66: 0x2832ED74F2B5E35EE,
    67: 0x730FC235C1942C1AE,
    68: 0xBEBB3940CD0FC1491,
    69: 0x101D83275FB2BC7E0C,
    70: 0x349B84B6431A6C4EF1,
}


def puzzle_range(n: int) -> Tuple[int, int]:
    return 1 << (n - 1), (1 << n) - 1


def puzzle_prize_btc(n: int) -> float:
    return n / 10  # funding after the 2023 top-up: puzzle n holds n x 0.1 BTC


###############################################################################
# The scanner core (runs inside worker processes)
###############################################################################
HALF = 2048                 # keys on each side of a group centre
GROUP = 2 * HALF + 1        # keys per group (4097)

_TX: List[int] = []         # x of (i+1)*G, i < HALF
_TY: List[int] = []
_J: Point = None            # GROUP * G, moves the centre to the next group
_TARGETS: Set[bytes] = set()
_STOP = None                # multiprocessing.Event shared by all workers


def _build_tables() -> None:
    global _J
    if _TX:
        return
    q = G
    for _ in range(HALF):
        _TX.append(q[0])
        _TY.append(q[1])
        q = ec_add(q, G)
    _J = ec_mul(GROUP)


class _NoStop:
    @staticmethod
    def is_set() -> bool:
        return False


def scan_range(a: int, b: int, targets: Set[bytes], stop=None) -> Tuple[int, List[int], bool]:
    """
    Check every private key in [a, b] (inclusive, 1 <= a <= b < N).
    Returns (keys_checked, matching_keys, finished).

    Keys are visited in groups centred on c: c, c+1..c+m and c-1..c-m.
    For each i, (c +/- i)G = C +/- iG share the denominator x(iG) - x(C), so a
    single Montgomery batch inversion per group gives every slope.
    """
    if not (1 <= a <= b < N):
        raise ValueError("range must satisfy 1 <= start <= end < curve order")
    _build_tables()
    stop = stop or _NoStop
    sha = _sha256
    proto = _RMD_PROTO
    rmd = ripemd160
    pref = (b"\x02", b"\x03")
    hits: List[int] = []
    checked = 0
    k = a
    cx = cy = None
    while k <= b:
        if stop.is_set():
            return checked, hits, False
        rem = b - k + 1
        m = HALF if rem >= GROUP else (rem - 1) // 2
        c = k + m
        if cx is None or m != HALF:
            cx, cy = ec_mul(c)
        TX = _TX if m == HALF else _TX[:m]
        TY = _TY if m == HALF else _TY[:m]

        # centre
        pub = pref[cy & 1] + cx.to_bytes(32, "big")
        if proto is not None:
            r = proto.copy(); r.update(sha(pub).digest()); h = r.digest()
        else:
            h = rmd(sha(pub).digest())
        if h in targets:
            hits.append(c)

        if m:
            # Montgomery batch inversion of (x(iG) - x(C)) for i = 1..m
            acc = []
            t = 1
            for tx in TX:
                t = t * (tx - cx) % P
                acc.append(t)
            inv = pow(t, -1, P)
            invs = [0] * m
            for i in range(m - 1, 0, -1):
                invs[i] = inv * acc[i - 1] % P
                inv = inv * (TX[i] - cx) % P
            invs[0] = inv

            i = 1
            if proto is not None:
                for tx, ty, iv in zip(TX, TY, invs):
                    lam = (ty - cy) * iv % P                    # C + iG
                    x3 = (lam * lam - cx - tx) % P
                    y3 = (lam * (cx - x3) - cy) % P
                    r = proto.copy(); r.update(sha(pref[y3 & 1] + x3.to_bytes(32, "big")).digest())
                    if r.digest() in targets:
                        hits.append(c + i)
                    lam = -(ty + cy) * iv % P                   # C - iG
                    x3 = (lam * lam - cx - tx) % P
                    y3 = (lam * (cx - x3) - cy) % P
                    r = proto.copy(); r.update(sha(pref[y3 & 1] + x3.to_bytes(32, "big")).digest())
                    if r.digest() in targets:
                        hits.append(c - i)
                    i += 1
            else:
                for tx, ty, iv in zip(TX, TY, invs):
                    lam = (ty - cy) * iv % P
                    x3 = (lam * lam - cx - tx) % P
                    y3 = (lam * (cx - x3) - cy) % P
                    if rmd(sha(pref[y3 & 1] + x3.to_bytes(32, "big")).digest()) in targets:
                        hits.append(c + i)
                    lam = -(ty + cy) * iv % P
                    x3 = (lam * lam - cx - tx) % P
                    y3 = (lam * (cx - x3) - cy) % P
                    if rmd(sha(pref[y3 & 1] + x3.to_bytes(32, "big")).digest()) in targets:
                        hits.append(c - i)
                    i += 1

        n = 2 * m + 1
        if m < HALF and rem == n + 1:      # even remainder: one key left (c+m+1)
            ex, ey = ec_add((cx, cy), (_TX[m], _TY[m]))
            if hash160(pref[ey & 1] + ex.to_bytes(32, "big")) in targets:
                hits.append(c + m + 1)
            n += 1
        checked += n
        k += n
        if m == HALF and b - k + 1 >= GROUP:
            cx, cy = ec_add((cx, cy), _J)  # next centre = c + GROUP
        else:
            cx = None
    return checked, hits, True


def _worker_init(targets: Set[bytes], stop_event) -> None:
    global _TARGETS, _STOP
    try:
        signal.signal(signal.SIGINT, signal.SIG_IGN)  # the main process handles Ctrl+C
    except (ValueError, OSError):
        pass
    if hasattr(os, "nice"):
        try:
            os.nice(5)  # stay polite to the rest of the machine
        except OSError:
            pass
    _TARGETS = targets
    _STOP = stop_event
    _build_tables()


def _worker_task(task: Tuple[int, int, int, int]) -> dict:
    job, idx, a, b = task
    t0 = time.perf_counter()
    keys, hits, finished = scan_range(a, b, _TARGETS, _STOP)
    return {"job": job, "idx": idx, "keys": keys, "hits": hits,
            "finished": finished, "secs": time.perf_counter() - t0}


###############################################################################
# Formatting helpers
###############################################################################
def fmt_num(x: float) -> str:
    if abs(x) >= 1e15:
        return f"{x:.3g}"
    for unit, div in (("T", 1e12), ("G", 1e9), ("M", 1e6), ("k", 1e3)):
        if abs(x) >= div:
            return f"{x / div:.2f}{unit}"
    return f"{x:.0f}"


def fmt_duration(sec: float) -> str:
    if sec == float("inf") or sec != sec:
        return "forever"
    if sec < 120:
        return f"{sec:.0f} s"
    if sec < 7200:
        return f"{sec / 60:.0f} min"
    if sec < 172800:
        return f"{sec / 3600:.1f} h"
    days = sec / 86400
    if days < 730:
        return f"{days:.0f} days"
    years = days / 365.25
    for word, div in (("trillion", 1e12), ("billion", 1e9), ("million", 1e6), ("thousand", 1e3)):
        if years >= div:
            return f"{years / div:,.1f} {word} years"
    return f"{years:,.0f} years"


def fmt_pct(x: float) -> str:
    if x == 0:
        return "0%"
    if x < 1e-4:
        return f"{x:.2e}%"
    return f"{x:.4f}%"


###############################################################################
# Persistent state (SQLite)
###############################################################################
class StateDB:
    def __init__(self, path: str):
        self.path = path
        self.conn = sqlite3.connect(path, timeout=30)
        self.conn.execute("PRAGMA journal_mode=WAL")
        self.conn.executescript("""
            CREATE TABLE IF NOT EXISTS jobs(
                job_key TEXT PRIMARY KEY, label TEXT, start_hex TEXT, end_hex TEXT,
                chunk_size INTEGER, frontier_hex TEXT DEFAULT '0',
                keys_done INTEGER DEFAULT 0, chunks_done INTEGER DEFAULT 0, updated TEXT);
            CREATE TABLE IF NOT EXISTS chunks(
                job_key TEXT, idx TEXT, PRIMARY KEY(job_key, idx)) WITHOUT ROWID;
            CREATE TABLE IF NOT EXISTS found(
                ts TEXT, label TEXT, address TEXT, key_hex TEXT, wif TEXT);
        """)
        self.conn.commit()

    @staticmethod
    def _ix(idx: int) -> str:
        return format(idx, "032x")  # fixed width, so text order == numeric order

    def load_job(self, job) -> None:
        row = self.conn.execute(
            "SELECT frontier_hex, keys_done, chunks_done FROM jobs WHERE job_key=?", (job.key,)).fetchone()
        if row is None:
            self.conn.execute(
                "INSERT INTO jobs(job_key,label,start_hex,end_hex,chunk_size,updated) VALUES(?,?,?,?,?,datetime('now'))",
                (job.key, job.label, hex(job.start), hex(job.end), job.chunk_size))
            self.conn.commit()
            return
        job.frontier = int(row[0], 16)
        job.keys_done = int(row[1])
        job.chunks_done = int(row[2])

    def done_above(self, job, frontier: int, limit: int = 5_000_000) -> Set[int]:
        rows = self.conn.execute(
            "SELECT idx FROM chunks WHERE job_key=? AND idx>=? LIMIT ?", (job.key, self._ix(frontier), limit))
        return {int(r[0], 16) for r in rows}

    def is_done(self, job, idx: int) -> bool:
        return self.conn.execute(
            "SELECT 1 FROM chunks WHERE job_key=? AND idx=?", (job.key, self._ix(idx))).fetchone() is not None

    def mark_done(self, job, idx: int, keys: int) -> None:
        self.conn.execute("INSERT OR IGNORE INTO chunks(job_key, idx) VALUES(?,?)", (job.key, self._ix(idx)))
        self.conn.execute(
            "UPDATE jobs SET frontier_hex=?, keys_done=?, chunks_done=?, updated=datetime('now') WHERE job_key=?",
            (hex(job.frontier), job.keys_done, job.chunks_done, job.key))
        self.conn.commit()

    def record_found(self, label: str, address: str, key: int) -> None:
        self.conn.execute("INSERT INTO found VALUES(datetime('now'),?,?,?,?)",
                          (label, address, format(key, "064x"), key_to_wif(key)))
        self.conn.commit()

    def close(self) -> None:
        self.conn.close()


###############################################################################
# Jobs and task planning
###############################################################################
@dataclass
class Job:
    label: str
    addresses: List[str]
    start: int
    end: int
    chunk_size: int
    puzzle: Optional[int] = None
    frontier: int = 0          # sequential: every chunk below this is done
    keys_done: int = 0
    chunks_done: int = 0
    next_idx: int = 0
    done_set: Set[int] = field(default_factory=set)
    inflight: Set[int] = field(default_factory=set)
    exhausted: bool = False

    @property
    def size(self) -> int:
        return self.end - self.start + 1

    @property
    def nchunks(self) -> int:
        return (self.size + self.chunk_size - 1) // self.chunk_size

    @property
    def key(self) -> str:
        return f"{self.label}|{self.start:x}|{self.end:x}|cs{self.chunk_size}"

    def chunk_bounds(self, idx: int) -> Tuple[int, int]:
        a = self.start + idx * self.chunk_size
        return a, min(self.end, a + self.chunk_size - 1)


class Planner:
    """Hands out chunks: sequential (round-robin across jobs) or random."""

    def __init__(self, jobs: List[Job], mode: str, db: StateDB):
        self.jobs = jobs
        self.mode = mode
        self.db = db
        self.rr = 0
        for j in jobs:
            db.load_job(j)
            j.next_idx = j.frontier
            if mode == "sequential":
                j.done_set = db.done_above(j, j.frontier)
            if j.chunks_done >= j.nchunks:
                j.exhausted = True

    def active(self) -> List[Job]:
        return [j for j in self.jobs if not j.exhausted]

    def next_task(self) -> Optional[Tuple[int, int, int, int]]:
        if self.mode == "sequential":
            return self._next_sequential()
        return self._next_random()

    def _next_sequential(self):
        for _ in range(len(self.jobs)):
            ji = self.rr % len(self.jobs)
            self.rr += 1
            j = self.jobs[ji]
            if j.exhausted:
                continue
            while j.next_idx < j.nchunks and j.next_idx in j.done_set:
                j.next_idx += 1
            if j.next_idx >= j.nchunks:
                continue  # everything dispatched; exhausted once in-flight work lands
            idx = j.next_idx
            j.next_idx += 1
            j.inflight.add(idx)
            return (ji, idx) + j.chunk_bounds(idx)
        return None

    def _next_random(self):
        jobs = [(i, j) for i, j in enumerate(self.jobs)
                if not j.exhausted and j.chunks_done + len(j.inflight) < j.nchunks]
        if not jobs:
            return None
        ji, j = jobs[secrets.randbelow(len(jobs))]
        for _ in range(64):
            idx = secrets.randbelow(j.nchunks)
            if idx not in j.inflight and not self.db.is_done(j, idx):
                break
        else:  # small, nearly finished range: take the first free chunk
            idx = next((x for x in range(j.nchunks)
                        if x not in j.inflight and not self.db.is_done(j, x)), None)
            if idx is None:
                return None
        j.inflight.add(idx)
        return (ji, idx) + j.chunk_bounds(idx)

    def complete(self, ji: int, idx: int, keys: int, finished: bool) -> None:
        j = self.jobs[ji]
        j.inflight.discard(idx)
        if not finished:
            if self.mode == "sequential":
                j.next_idx = min(j.next_idx, idx)  # redo it next time
            return
        j.keys_done += keys
        j.chunks_done += 1
        if self.mode == "sequential":
            j.done_set.add(idx)
            while j.frontier in j.done_set:
                j.done_set.discard(j.frontier)
                j.frontier += 1
        self.db.mark_done(j, idx, keys)
        if j.chunks_done >= j.nchunks:
            j.exhausted = True


###############################################################################
# Scan driver
###############################################################################
FOUND_BANNER = """
###############################################################################
#  KEY FOUND - {label}
#  address : {address}
#  key hex : {key_hex}
#  WIF     : {wif}
#  saved to: {path}
#
#  DO NOT broadcast a spend through the public mempool. A spend reveals the
#  public key, and a key this small is recovered with Pollard's kangaroo in
#  seconds: bots will replace your transaction with a higher-fee one. Submit
#  it privately to a mining pool (non-public transaction submission).
###############################################################################
"""


def save_found(path: str, label: str, address: str, key: int) -> None:
    line = (f"{time.strftime('%Y-%m-%d %H:%M:%S')} | {label} | {address} | "
            f"hex={key:064x} | WIF={key_to_wif(key)}\n")
    with open(path, "a", encoding="utf-8") as f:
        f.write(line)
        f.flush()
        os.fsync(f.fileno())


def run_scan(jobs: List[Job], mode: str, workers: int, state_path: str, found_path: str,
             status_every: float = 15.0, stop_file: Optional[str] = "STOP",
             stop_on_found: bool = True, announce: bool = True) -> List[Tuple[str, str, int]]:
    """Run the scan; returns a list of (label, address, key) found."""
    targets: Dict[bytes, Tuple[str, str]] = {}
    for j in jobs:
        for addr in j.addresses:
            targets[address_to_hash160(addr)] = (j.label, addr)
    target_set = set(targets)

    db = StateDB(state_path)
    planner = Planner(jobs, mode, db)
    for j in jobs[:4]:
        log.info("%s: range %s..%s (%s keys, %s chunks of %s), already scanned %s",
                 j.label, hex(j.start), hex(j.end), fmt_num(j.size), fmt_num(j.nchunks),
                 fmt_num(j.chunk_size), fmt_pct(100 * j.keys_done / j.size))
    if len(jobs) > 4:
        log.info("... and %d more ranges: %s", len(jobs) - 4, " ".join(j.label for j in jobs[4:]))
    if not planner.active():
        log.info("Nothing left to scan for these ranges (all chunks done). Use another range or --state file.")
        db.close()
        return []

    ctx = mp.get_context("spawn")
    stop_event = ctx.Event()
    found: List[Tuple[str, str, int]] = []
    session_keys = 0
    t_start = time.time()
    t_status = t_start
    stopping = False
    max_inflight = workers * 2

    def handle_hits(res: dict) -> None:
        for k in res["hits"]:
            h = hash160(pubkey_compressed(k))  # independent re-check, not the batched path
            if h not in targets:
                log.error("Worker reported key %s but it does not verify - please report this.", hex(k))
                continue
            label, addr = targets[h]
            save_found(found_path, label, addr, k)
            db.record_found(label, addr, k)
            found.append((label, addr, k))
            if announce:
                print(FOUND_BANNER.format(label=label, address=addr, key_hex=f"{k:064x}",
                                          wif=key_to_wif(k), path=os.path.abspath(found_path)), flush=True)
            else:
                log.info("found %s key %s", label, hex(k))

    log.info("Starting %d worker(s), mode=%s, RIPEMD-160 backend: %s", workers, mode, RIPEMD_BACKEND)
    pool = cf.ProcessPoolExecutor(max_workers=workers, mp_context=ctx,
                                  initializer=_worker_init, initargs=(target_set, stop_event))
    inflight: Dict[cf.Future, Tuple[int, int, int, int]] = {}
    try:
        while True:
            while not stopping and len(inflight) < max_inflight:
                task = planner.next_task()
                if task is None:
                    break
                inflight[pool.submit(_worker_task, task)] = task
            if not inflight:
                break
            done, _ = cf.wait(list(inflight), timeout=1.0, return_when=cf.FIRST_COMPLETED)
            for fut in done:
                inflight.pop(fut)
                res = fut.result()
                session_keys += res["keys"]
                handle_hits(res)
                planner.complete(res["job"], res["idx"], res["keys"], res["finished"])
                if found and stop_on_found and not stopping:
                    stopping = True
                    stop_event.set()
            now = time.time()
            if stop_file and not stopping and os.path.exists(stop_file):
                log.info("Stop file %r found - finishing current chunks and saving.", stop_file)
                stopping = True
                stop_event.set()
            if now - t_status >= status_every:
                t_status = now
                rate = session_keys / max(now - t_start, 1e-9)
                parts = []
                for j in jobs[:3]:
                    full = j.size / rate if rate else float("inf")
                    parts.append(f"{j.label} {fmt_pct(100 * j.keys_done / j.size)} scanned, "
                                 f"full range at this speed: {fmt_duration(full)}")
                if len(jobs) > 3:
                    parts.append(f"+{len(jobs) - 3} more ranges")
                log.info("%s keys this session | %s keys/s | %s", fmt_num(session_keys), fmt_num(rate),
                         " | ".join(parts))
    except KeyboardInterrupt:
        log.info("Stop requested - stopping workers and saving progress (Ctrl+C again to force quit)...")
        stop_event.set()
        try:
            for fut in cf.as_completed(list(inflight)):
                inflight.pop(fut)
                try:
                    res = fut.result()
                except Exception:
                    continue
                session_keys += res["keys"]
                handle_hits(res)
                planner.complete(res["job"], res["idx"], res["keys"], res["finished"])
        except KeyboardInterrupt:
            pass
    finally:
        stop_event.set()
        if sys.version_info >= (3, 9):
            pool.shutdown(wait=True, cancel_futures=True)
        else:
            pool.shutdown(wait=True)
        db.close()

    elapsed = time.time() - t_start
    log.info("Session: %s keys in %s (%s keys/s). Unfinished chunks are redone next run.",
             fmt_num(session_keys), fmt_duration(elapsed), fmt_num(session_keys / max(elapsed, 1e-9)))
    if not found and not planner.active():
        log.info("Range fully scanned - no match.")
    return found


###############################################################################
# Commands
###############################################################################
def parse_puzzles(spec: str) -> List[int]:
    out: List[int] = []
    for part in spec.split(","):
        part = part.strip()
        if "-" in part:
            lo, hi = (int(x) for x in part.split("-", 1))
            out.extend(range(lo, hi + 1))
        elif part:
            out.append(int(part))
    bad = [n for n in out if n not in PUZZLES]
    if bad:
        raise SystemExit(f"Unknown puzzle(s) {bad}. Built in: #{min(PUZZLES)}-#{max(PUZZLES)}.")
    return sorted(set(out))


def parse_pos(text: str, lo: int, hi: int) -> int:
    """hex (0x optional), 'dec:<n>', or 'x%' of [lo, hi]."""
    s = text.strip().lower().replace("_", "")
    if s.endswith("%"):
        frac = Fraction(s[:-1]) / 100
        if not 0 <= frac <= 1:
            raise SystemExit(f"Percentage out of range: {text}")
        return lo + int((hi - lo) * frac)
    if s.startswith("dec:"):
        return int(s[4:], 10)
    return int(s[2:] if s.startswith("0x") else s, 16)


def apply_shard(lo: int, hi: int, shard: str) -> Tuple[int, int]:
    i, n = (int(x) for x in shard.split("/"))
    if not 1 <= i <= n:
        raise SystemExit("--shard must look like 3/8 (part 3 of 8, 1-based)")
    size = hi - lo + 1
    a = lo + size * (i - 1) // n
    b = lo + size * i // n - 1
    return a, b


def build_jobs(args) -> List[Job]:
    chunk = 1 << args.chunk_bits
    jobs: List[Job] = []
    if args.address:
        if args.puzzle:
            raise SystemExit("Use either --puzzle or --address, not both.")
        if not (args.start and args.end):
            raise SystemExit("--address needs --start and --end (hex).")
        for a in args.address:
            try:
                address_to_hash160(a)  # validate early
            except ValueError as e:
                raise SystemExit(f"Bad --address: {e}")
        lo = parse_pos(args.start, 1, N - 1)
        hi = parse_pos(args.end, 1, N - 1)
        if args.shard:
            lo, hi = apply_shard(lo, hi, args.shard)
        jobs.append(Job("custom", list(args.address), lo, hi, chunk))
    else:
        if not args.puzzle:
            raise SystemExit("Give --puzzle (e.g. 71 or 71-100) or --address with --start/--end.")
        nums = parse_puzzles(args.puzzle)
        if not args.include_solved:
            skipped = [n for n in nums if n in KNOWN_SOLVED]
            nums = [n for n in nums if n not in KNOWN_SOLVED]
            if skipped:
                log.info("Skipping known-solved puzzle(s) %s (use --include-solved to scan them anyway).",
                         ", ".join(f"#{n}" for n in skipped))
        if not nums:
            raise SystemExit("No puzzles left to scan.")
        if len(nums) > 1 and not all(x.strip().endswith("%") for x in (args.start, args.end) if x):
            raise SystemExit("With several puzzles, --start/--end must be percentages (e.g. 25%).")
        for n in nums:
            lo, hi = puzzle_range(n)
            a = parse_pos(args.start, lo, hi) if args.start else lo
            b = parse_pos(args.end, lo, hi) if args.end else hi
            if not (lo <= a <= b <= hi):
                raise SystemExit(f"#{n}: range {hex(a)}..{hex(b)} is outside the puzzle range {hex(lo)}..{hex(hi)}")
            if args.shard:
                a, b = apply_shard(a, b, args.shard)
            jobs.append(Job(f"#{n}", [PUZZLES[n]], a, b, chunk, puzzle=n))
    for j in jobs:
        if not (1 <= j.start <= j.end < N):
            raise SystemExit(f"{j.label}: invalid range {hex(j.start)}..{hex(j.end)}")
    return jobs


def cmd_scan(args) -> int:
    jobs = build_jobs(args)
    mode = args.mode
    if mode == "auto":
        mode = "random" if max(j.size for j in jobs) > (1 << 48) else "sequential"
    if len([j for j in jobs if j.puzzle]) > 1:
        smallest = min(j.puzzle for j in jobs if j.puzzle)
        log.info("Note: a key checked in #%d is 2^%d times more likely to win than one in #%d. "
                 "Chunks are split evenly across the selected puzzles.",
                 smallest, max(j.puzzle for j in jobs if j.puzzle) - smallest, max(j.puzzle for j in jobs if j.puzzle))
    run_scan(jobs, mode, args.workers, args.state, args.found,
             status_every=args.status_every, stop_file=args.stop_file)
    return 0


def fetch_balance(addr: str, timeout: float = 15.0) -> Optional[Tuple[int, int]]:
    """(balance_sat, tx_count) from mempool.space, or None on error."""
    try:
        req = urllib.request.Request(f"https://mempool.space/api/address/{addr}",
                                     headers={"User-Agent": f"dqx-scan/{__version__}"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            d = json.loads(r.read().decode())
        cs, ms = d["chain_stats"], d["mempool_stats"]
        bal = cs["funded_txo_sum"] - cs["spent_txo_sum"] + ms["funded_txo_sum"] - ms["spent_txo_sum"]
        return bal, cs["tx_count"] + ms["tx_count"]
    except Exception as e:  # network errors are expected offline
        log.debug("balance lookup failed for %s: %s", addr, e)
        return None


def cmd_list(args) -> int:
    nums = parse_puzzles(args.puzzle) if args.puzzle else [n for n in PUZZLES if n >= 71]
    rate = args.rate
    print(f"{'#':>4}  {'address':<35} {'range start':>28}  {'keys':<6} {'prize':>9}  status")
    for n in nums:
        lo, hi = puzzle_range(n)
        status = "solved" if n in KNOWN_SOLVED else "unsolved"
        if args.online:
            res = fetch_balance(PUZZLES[n])
            status = "lookup failed" if res is None else (
                f"{res[0] / 1e8:.8f} BTC" + (" (empty)" if res[0] == 0 else ""))
        print(f"{n:>4}  {PUZZLES[n]:<35} {hex(lo):>28}  2^{n - 1:<4} {puzzle_prize_btc(n):>5.1f} BTC  {status}")
    print(f"\nKeys in puzzle #n: 2^(n-1). At {fmt_num(rate)} keys/s (change with --rate):")
    for n in [x for x in nums if x not in KNOWN_SOLVED][:6]:
        size = 1 << (n - 1)
        print(f"  #{n}: full scan {fmt_duration(size / rate)}, "
              f"chance to win per day {86400 * rate / size:.2e}")
    return 0


def cmd_bench(args) -> int:
    _build_tables()
    print(f"RIPEMD-160 backend: {RIPEMD_BACKEND}")
    a = (1 << 70) + secrets.randbelow(1 << 69)
    t0 = time.perf_counter()
    n = 0
    while time.perf_counter() - t0 < args.seconds / 2:
        k, _, _ = scan_range(a + n, a + n + 50 * GROUP - 1, set())
        n += k
    single = n / (time.perf_counter() - t0)
    print(f"1 core : {fmt_num(single)} keys/s")

    ctx = mp.get_context("spawn")
    ev = ctx.Event()
    chunk = 200 * GROUP
    with cf.ProcessPoolExecutor(max_workers=args.workers, mp_context=ctx,
                                initializer=_worker_init, initargs=(set(), ev)) as pool:
        list(pool.map(_worker_task, [(0, i, a, a + GROUP) for i in range(args.workers)]))  # warm-up
        t0 = time.perf_counter()
        total = 0
        i = 0
        futs = set()
        while time.perf_counter() - t0 < args.seconds or futs:
            while len(futs) < args.workers * 2 and time.perf_counter() - t0 < args.seconds:
                s = a + i * chunk
                futs.add(pool.submit(_worker_task, (0, i, s, s + chunk - 1)))
                i += 1
            done, futs = cf.wait(futs, return_when=cf.FIRST_COMPLETED)
            total += sum(f.result()["keys"] for f in done)
        multi = total / (time.perf_counter() - t0)
    print(f"{args.workers} cores: {fmt_num(multi)} keys/s\n")
    print(f"{'puzzle':>6}  {'expected (50%)':>22}  {'full range':>22}")
    for n in [71, 72, 73, 74, 76, 80, 90, 99]:
        size = 1 << (n - 1)
        print(f"{'#' + str(n):>6}  {fmt_duration(size / 2 / multi):>22}  {fmt_duration(size / multi):>22}")
    print("\nFor reference, public pools scan around 10^11 keys/s on GPUs.")
    return 0


def cmd_selftest(args) -> int:
    ok = True

    def check(name, cond):
        nonlocal ok
        ok &= bool(cond)
        print(f"  [{'PASS' if cond else 'FAIL'}] {name}")

    print(f"RIPEMD-160 backend: {RIPEMD_BACKEND}")
    print("Primitives")
    check("RIPEMD-160 matches reference vector",
          ripemd160(b"abc").hex() == "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc")
    check("pure-Python RIPEMD-160 matches reference vector",
          _ripemd160_pure(b"abc").hex() == "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc")
    check("2G x-coordinate",
          ec_mul(2)[0] == 0xC6047F9441ED7D6D3045406E95C07CD85C778E4B8CEF3CA7ABAC09B95C709EE5)
    check("hash160(1*G) / address of key 1",
          hash160(pubkey_compressed(1)).hex() == "751e76e8199196d454941c45d1b3a323f1433bd6"
          and key_to_address(1) == "1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH")
    check("WIF of key 1", key_to_wif(1) == "KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn")
    check("all built-in puzzle addresses have valid checksums",
          all(len(address_to_hash160(a)) == 20 for a in PUZZLES.values()))

    print("Batched scanner vs. independent per-key derivation")
    rnd = random.Random(1234)
    for label, a, length in (("random 70-bit range", (1 << 70) + rnd.getrandbits(69), 3 * GROUP + 2),
                             ("odd tail", (1 << 71) + rnd.getrandbits(70), 2 * GROUP + 7),
                             ("tiny range", (1 << 72) + 5, 1),
                             ("bottom of curve", 1, GROUP + 40),
                             ("top of curve", N - 1 - GROUP - 10, GROUP + 11)):
        b = a + length - 1
        offs = sorted({0, length - 1, length // 2, min(HALF, length - 1), min(GROUP, length - 1),
                       min(GROUP + 1, length - 1)} | {rnd.randrange(length) for _ in range(5)})
        want = {a + o for o in offs}
        tg = {hash160(pubkey_compressed(k)) for k in want}
        keys, hits, fin = scan_range(a, b, tg)
        check(f"{label}: {length} keys, planted {len(want)} targets", fin and keys == length and set(hits) == want)

    try:
        import coincurve  # optional cross-check against libsecp256k1
        a = (1 << 75) + rnd.getrandbits(74)
        tg = {}
        for o in (0, 1, 777, 2049, 4096, 9000):
            pub = coincurve.PrivateKey.from_int(a + o).public_key.format(compressed=True)
            tg[hash160(pub)] = a + o
        _, hits, _ = scan_range(a, a + 9000, set(tg))
        check("cross-check with libsecp256k1 (coincurve)", set(hits) == set(tg.values()))
    except ImportError:
        print("  [skip] coincurve not installed (optional libsecp256k1 cross-check)")

    print("Solved puzzles (real data)")
    for n, k in SOLVED_KEYS.items():
        lo, hi = puzzle_range(n)
        check(f"#{n}: published key derives {PUZZLES[n]}", lo <= k <= hi and key_to_address(k) == PUZZLES[n])

    print("Full pipeline (worker processes, checkpoint DB, found file)")
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        jobs = [Job("#67-window", [PUZZLES[67]], 0x730FC235C1942C1A0 - 10 ** 6, 0x730FC235C1942C2AE, 1 << 18),
                Job("#68-window", [PUZZLES[68]], SOLVED_KEYS[68] - 3 * 10 ** 5, SOLVED_KEYS[68] + 10 ** 5, 1 << 18)]
        found = run_scan(jobs, "sequential", min(args.workers, 4), os.path.join(tmp, "s.db"),
                         os.path.join(tmp, "found.txt"), status_every=1e9, stop_file=None,
                         stop_on_found=False, announce=False)
        check("worker processes find the #67 and #68 keys inside 1.3M-key windows",
              sorted(k for _, _, k in found) == [SOLVED_KEYS[67], SOLVED_KEYS[68]])
        check("found file written with WIF", os.path.exists(os.path.join(tmp, "found.txt")))

        jobs = [Job("resume", [PUZZLES[71]], 1 << 70, (1 << 70) + 5 * (1 << 16) - 1, 1 << 16)]
        run_scan(jobs, "sequential", min(args.workers, 2), os.path.join(tmp, "r.db"),
                 os.path.join(tmp, "f2.txt"), status_every=1e9, stop_file=None, announce=False)
        jobs2 = [Job("resume", [PUZZLES[71]], 1 << 70, (1 << 70) + 5 * (1 << 16) - 1, 1 << 16)]
        db = StateDB(os.path.join(tmp, "r.db"))
        Planner(jobs2, "sequential", db)
        db.close()
        check("checkpoint: finished range is remembered (resume skips it)",
              jobs2[0].chunks_done == 5 and jobs2[0].keys_done == 5 * (1 << 16))
        jobs3 = [Job("resume", [PUZZLES[71]], 1 << 70, (1 << 70) + 6 * (1 << 16) - 1, 1 << 16)]
        db = StateDB(os.path.join(tmp, "r.db"))
        Planner(jobs3, "sequential", db)
        db.close()
        check("checkpoint: a different range does NOT reuse old progress", jobs3[0].keys_done == 0)

    print("\nALL TESTS PASSED" if ok else "\nSOME TESTS FAILED")
    return 0 if ok else 1


###############################################################################
# CLI
###############################################################################
def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="DQX Puzzle Scanner - exhaustive hash160 search over Bitcoin puzzle key ranges.",
        formatter_class=argparse.RawDescriptionHelpFormatter, epilog=__doc__.split("Commands", 1)[1])
    ap.add_argument("-v", "--verbose", action="store_true")
    ap.add_argument("--log-file", default="dqx_scan.log")
    sub = ap.add_subparsers(dest="cmd", required=True)
    cpu = os.cpu_count() or 1

    s = sub.add_parser("scan", help="search a puzzle or a custom range")
    s.add_argument("--puzzle", help="e.g. 71, 71-100, 71,72,73")
    s.add_argument("--address", action="append", help="custom P2PKH target (repeatable)")
    s.add_argument("--start", help="hex, dec:<n>, or percent of the puzzle range (inclusive)")
    s.add_argument("--end", help="hex, dec:<n>, or percent of the puzzle range (inclusive)")
    s.add_argument("--shard", help="i/n: scan only part i of n (split work across machines)")
    s.add_argument("--mode", choices=["auto", "random", "sequential"], default="auto",
                   help="auto = random for ranges > 2^48 keys, else sequential")
    s.add_argument("--workers", type=int, default=cpu, help=f"processes (default {cpu})")
    s.add_argument("--chunk-bits", type=int, default=21, help="chunk = 2^bits keys (default 21, ~8 s/core)")
    s.add_argument("--include-solved", action="store_true", help="allow known-solved puzzles")
    s.add_argument("--state", default="dqx_state.db", help="progress database")
    s.add_argument("--found", default="FOUND_KEYS.txt", help="where found keys are appended")
    s.add_argument("--status-every", type=float, default=15.0, help="seconds between status lines")
    s.add_argument("--stop-file", default="STOP", help="create this file to stop gracefully")
    s.set_defaults(func=cmd_scan)

    l_ = sub.add_parser("list", help="show puzzles, ranges and odds")
    l_.add_argument("--puzzle", help="subset, e.g. 71-80 (default 71-100)")
    l_.add_argument("--online", action="store_true", help="look up live balances on mempool.space")
    l_.add_argument("--rate", type=float, default=1e6, help="keys/s for the time estimates")
    l_.set_defaults(func=cmd_list)

    b = sub.add_parser("bench", help="measure keys/s on this machine")
    b.add_argument("--workers", type=int, default=cpu)
    b.add_argument("--seconds", type=float, default=10.0)
    b.set_defaults(func=cmd_bench)

    t = sub.add_parser("selftest", help="verify correctness on known data")
    t.add_argument("--workers", type=int, default=min(cpu, 4))
    t.set_defaults(func=cmd_selftest)

    args = ap.parse_args(argv)
    handlers: List[logging.Handler] = [logging.StreamHandler(sys.stdout)]
    if args.cmd == "scan" and args.log_file:
        handlers.append(logging.FileHandler(args.log_file, encoding="utf-8"))
    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s", handlers=handlers)
    if args.cmd in ("scan", "bench", "selftest") and getattr(args, "workers", 1) < 1:
        raise SystemExit("--workers must be >= 1")
    if args.cmd == "scan" and not 12 <= args.chunk_bits <= 40:
        raise SystemExit("--chunk-bits must be between 12 and 40")
    return args.func(args)


def _sigterm(signum, frame):
    raise KeyboardInterrupt  # treat `kill` / service stop like Ctrl+C: save and exit


if __name__ == "__main__":
    mp.freeze_support()
    if hasattr(signal, "SIGTERM"):
        signal.signal(signal.SIGTERM, _sigterm)
    sys.exit(main())
