# as alt2, but slots 2/5/11 get a third option

WORDS 18
TARGET 1KfZGvwZxsvSmemoCmEV75uqcNzYBHjkHZ
PATH m/44'/0'/0'/0/0
PATH m/0'/0/0
PATH m/0/0
PATH m/44'/0'/0'/0/1
SLOT 1  subject|section
SLOT 2  camera|twin|security
SLOT 3  tower|clock
SLOT 4  mask|face
SLOT 5  police|order|power
SLOT 6  @POOL
SLOT 7  liberty|torch
SLOT 8  @POOL
SLOT 9  eye|pyramid
SLOT 10 black|night
SLOT 11 pyramid|space|axis
SLOT 12 vote|debate
SLOT 13 moon|month
SLOT 14 @POOL
SLOT 15 @POOL
SLOT 16 rifle|gun
SLOT 17 gold|price
SLOT 18 @POOL
POOL accuse agree axis deal debate fire first food future gun hand life major
POOL maximum minimum mobile need news order paper payment phone power predict price proof
POOL punch receive security space stock there trade twin weapon welcome world
