# t18 with every fixed word shifted by -1

WORDS 18
TARGET 1KfZGvwZxsvSmemoCmEV75uqcNzYBHjkHZ
PATH m/44'/0'/0'/0/0
PATH m/0'/0/0
PATH m/0/0
PATH m/44'/0'/0'/0/1
SLOT 1  camera
SLOT 2  tower
SLOT 3  mask
SLOT 4  police
SLOT 5  @POOL
SLOT 6  liberty
SLOT 7  @POOL
SLOT 8  eye
SLOT 9  black
SLOT 10 pyramid
SLOT 11 vote
SLOT 12 moon
SLOT 13 @POOL
SLOT 14 @POOL
SLOT 15 rifle
SLOT 16 gold
SLOT 17 @POOL
SLOT 18 glove
POOL accuse agree axis deal debate fire first food future gun hand life major
POOL maximum minimum mobile need news order paper payment phone power predict price proof
POOL punch receive security space stock there trade twin weapon welcome world
