# t21 with every fixed word shifted by +1

WORDS 21
TARGET 1KfZGvwZxsvSmemoCmEV75uqcNzYBHjkHZ
PATH m/44'/0'/0'/0/0
PATH m/0'/0/0
PATH m/0/0
PATH m/44'/0'/0'/0/1
SLOT 1  @POOL
SLOT 2  subject
SLOT 3  camera
SLOT 4  tower
SLOT 5  mask
SLOT 6  police
SLOT 7  @POOL
SLOT 8  liberty
SLOT 9  @POOL
SLOT 10 eye
SLOT 11 black
SLOT 12 pyramid
SLOT 13 vote
SLOT 14 moon
SLOT 15 @POOL
SLOT 16 @POOL
SLOT 17 rifle
SLOT 18 gold
SLOT 19 @POOL
SLOT 20 glove
SLOT 21 apple|second
POOL accuse agree axis deal debate fire first food future gun hand life major
POOL maximum minimum mobile need news order paper payment phone power predict price proof
POOL punch receive security space stock there trade twin weapon welcome world
